#CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_KEYBOARD_NAME="KBHTotem"

# adding zmk sleep not compatible with hardware looking for a new option
CONFIG_ZMK_SLEEP=y
# setting sleep time 15mins
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_STUDIO=y