#CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_KEYBOARD_NAME="KBHTotem"

# adding zmk sleep not compatible with hardware looking for a new option
CONFIG_ZMK_SLEEP=y
# setting sleep time 15mins
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_POINTING=y
# comment out below to reduce battery use. This is increased for users with bad bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y